name: Daily batch      # line 1 ok

on:                    # line 3 must have the colon
  schedule:
    - cron:  '0 4 * * *'      # every day 04:00 UTC
    - cron:  '0 3 * * 0'      # Sunday 03:00 UTC
  workflow_dispatch:          # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENAI_KEY:        ${{ secrets.OPENAI_KEY }}
      REDDIT_CLIENT_ID:  ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_SECRET:     ${{ secrets.REDDIT_SECRET }}
      REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
      E11_KEY:           ${{ secrets.E11_KEY }}
      PEXELS_KEY:        ${{ secrets.PEXELS_KEY }}
      # Uncomment if you added these:
      # REDDIT_USERNAME:   ${{ secrets.REDDIT_USERNAME }}
      # REDDIT_PASSWORD:   ${{ secrets.REDDIT_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache remotion binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/remotion
          key: remotion-v1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Install Node deps
        run: npm ci

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # ---------- DEBUG BLOCK ----------
      - name: DEBUG – show Reddit env
        run: |
          echo "CID=[$REDDIT_CLIENT_ID]"
          echo "SECRET length=${#REDDIT_SECRET}"
          echo "UA=[$REDDIT_USER_AGENT]"
          python - <<'PY'
import os, praw
print("\nPRAW self-test:")
try:
    reddit = praw.Reddit(
        client_id=os.getenv("REDDIT_CLIENT_ID"),
        client_secret=os.getenv("REDDIT_SECRET"),
        user_agent=os.getenv("REDDIT_USER_AGENT"),
        # username=os.getenv("REDDIT_USERNAME"),  # if added
        # password=os.getenv("REDDIT_PASSWORD"),  # if added
        check_for_async=False,
    )
    print("read_only =", reddit.read_only)
    print("my_username =", reddit.user.me())
except Exception as e:
    print("EXCEPTION:", e)
PY
        env:
          REDDIT_CLIENT_ID:  ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_SECRET:     ${{ secrets.REDDIT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
      # ---------------------------------

      - name: Run batch
        run: make daily

      - name: Upload shorts
        uses: actions/upload-artifact@v4
        with:
          name: shorts
          path: out/*.mp4
          retention-days: 7
