name: Quick Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      OPENAI_KEY:        ${{ secrets.OPENAI_KEY }}
      REDDIT_CLIENT_ID:  ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_SECRET:     ${{ secrets.REDDIT_SECRET }}
      REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
      REDDIT_USERNAME:   ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD:   ${{ secrets.REDDIT_PASSWORD }}
      E11_KEY:           ${{ secrets.E11_KEY }}
      E11_VOICE:         ${{ secrets.E11_VOICE }}
      PEXELS_KEY:        ${{ secrets.PEXELS_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache Remotion binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/remotion
          key: remotion-v1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Install Node deps
        run: npm ci

      - name: Install ffmpeg and jq
        run: sudo apt-get update && sudo apt-get install -y ffmpeg jq

      - name: Run quick test
        run: make test

      - name: Upload test video
        uses: actions/upload-artifact@v4
        with:
          name: test-video
          path: out/test_video.mp4
          retention-days: 3

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            hooks.csv
            scripts.json
            clean.json
          retention-days: 3
